{{- if and .Values.mariadb.enabled (eq .Values.mariadb.architecture "replication") }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "mariadb.secondary.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.mariadb.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/component: secondary
  {{- if .Values.mariadb.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.mariadb.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.mariadb.secondary.replicaCount }}
  revisionHistoryLimit: {{ .Values.mariadb.secondary.revisionHistoryLimit }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.mariadb.secondary.podLabels .Values.mariadb.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/part-of: mariadb
      app.kubernetes.io/component: secondary
  serviceName: {{ printf "%s-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  {{- if .Values.mariadb.secondary.updateStrategy }}
  updateStrategy: {{- toYaml .Values.mariadb.secondary.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "mariadb.secondary.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/mariadb/secondary/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.mariadb.secondary.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/part-of: mariadb
        app.kubernetes.io/component: secondary
    spec:
      {{- include "mariadb.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.mariadb.secondary.automountServiceAccountToken }}
      serviceAccountName: {{ template "mariadb.serviceAccountName" . }}
      {{- if .Values.mariadb.secondary.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mariadb.secondary.podAffinityPreset "component" "secondary" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mariadb.secondary.podAntiAffinityPreset "component" "secondary" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.mariadb.secondary.nodeAffinityPreset.type "key" .Values.mariadb.secondary.nodeAffinityPreset.key "values" .Values.mariadb.secondary.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.mariadb.secondary.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mariadb.secondary.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mariadb.secondary.priorityClassName }}
      priorityClassName: {{ .Values.mariadb.secondary.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.mariadb.secondary.schedulerName }}
      schedulerName: {{ .Values.mariadb.secondary.schedulerName }}
      {{- end }}
      {{- if .Values.mariadb.secondary.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.mariadb.secondary.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: mariadb
          image: {{ include "mariadb.image" . }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy | quote }}
          {{- if .Values.mariadb.secondary.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.mariadb.secondary.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            # Official MariaDB image environment variables for replication secondary
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" . }}
                  key: mariadb-root-password
            {{- if not (empty .Values.mariadb.auth.username) }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" . }}
                  key: mariadb-password
            {{- end }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: MYSQL_REPLICATION_MODE
              value: "slave"
            - name: MYSQL_MASTER_HOST
              value: {{ include "mariadb.primary.fullname" . }}
            - name: MYSQL_MASTER_PORT
              value: {{ .Values.mariadb.primary.service.ports.mysql | quote }}
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" . }}
                  key: mariadb-root-password
            {{- if .Values.mariadb.secondary.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mariadb.secondary.containerPorts.mysql }}
          {{- if not .Values.mariadb.diagnosticMode.enabled }}
          {{- if .Values.mariadb.secondary.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.mariadb.secondary.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: {{ .Values.mariadb.secondary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mariadb.secondary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mariadb.secondary.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mariadb.secondary.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.mariadb.secondary.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.mariadb.secondary.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.mariadb.secondary.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: {{ .Values.mariadb.secondary.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mariadb.secondary.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mariadb.secondary.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mariadb.secondary.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.mariadb.secondary.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.mariadb.secondary.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.mariadb.secondary.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: {{ .Values.mariadb.secondary.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mariadb.secondary.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mariadb.secondary.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mariadb.secondary.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.mariadb.secondary.startupProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          {{- if .Values.mariadb.secondary.resources }}
          resources: {{- toYaml .Values.mariadb.secondary.resources | nindent 12 }}
          {{- else if ne .Values.mariadb.secondary.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.mariadb.secondary.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              {{- if .Values.mariadb.secondary.persistence.subPath }}
              subPath: {{ .Values.mariadb.secondary.persistence.subPath }}
              {{- end }}
            - name: tmp
              mountPath: /tmp
            - name: run-mysqld
              mountPath: /run/mysqld
            {{- if or .Values.mariadb.secondary.configuration .Values.mariadb.secondary.existingConfigmap }}
            - name: config
              mountPath: /etc/mysql/conf.d
            {{- end }}
            {{- if .Values.mariadb.secondary.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.mariadb.secondary.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: run-mysqld
          emptyDir: {}
        {{- if or .Values.mariadb.secondary.configuration .Values.mariadb.secondary.existingConfigmap }}
        - name: config
          configMap:
            name: {{ include "mariadb.secondary.configmapName" . }}
        {{- end }}
        {{- if .Values.mariadb.secondary.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
  {{- if .Values.mariadb.secondary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 10 }}
          app.kubernetes.io/component: secondary
        {{- if .Values.mariadb.secondary.persistence.annotations }}
        annotations: {{- toYaml .Values.mariadb.secondary.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.mariadb.secondary.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.mariadb.secondary.persistence.size | quote }}
        {{- if .Values.mariadb.secondary.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.secondary.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- include "common.storage.class" (dict "persistence" .Values.mariadb.secondary.persistence "global" .Values.global) | nindent 8 }}
  {{- else }}
        - name: data
          emptyDir: {}
  {{- end }}
{{- end }}
