{{- if .Values.mariadb.enabled }}
apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "mariadb.primary.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.mariadb.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/component: primary
  {{- if .Values.mariadb.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.mariadb.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.mariadb.primary.revisionHistoryLimit }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.mariadb.primary.podLabels .Values.mariadb.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/part-of: mariadb
      app.kubernetes.io/component: primary
  serviceName: {{ printf "%s-headless" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  {{- if .Values.mariadb.primary.updateStrategy }}
  updateStrategy: {{- toYaml .Values.mariadb.primary.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if (include "mariadb.primary.createConfigmap" .) }}
        checksum/configuration: {{ include (print $.Template.BasePath "/mariadb/primary/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.mariadb.primary.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/part-of: mariadb
        app.kubernetes.io/component: primary
    spec:
      {{- include "mariadb.imagePullSecrets" . | nindent 6 }}
      automountServiceAccountToken: {{ .Values.mariadb.primary.automountServiceAccountToken }}
      serviceAccountName: {{ template "mariadb.serviceAccountName" . }}
      {{- if .Values.mariadb.primary.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mariadb.primary.podAffinityPreset "component" "primary" "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.mariadb.primary.podAntiAffinityPreset "component" "primary" "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.mariadb.primary.nodeAffinityPreset.type "key" .Values.mariadb.primary.nodeAffinityPreset.key "values" .Values.mariadb.primary.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.mariadb.primary.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mariadb.primary.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mariadb.primary.priorityClassName }}
      priorityClassName: {{ .Values.mariadb.primary.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.mariadb.primary.schedulerName }}
      schedulerName: {{ .Values.mariadb.primary.schedulerName }}
      {{- end }}
      {{- if .Values.mariadb.primary.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.mariadb.primary.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.mariadb.primary.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.mariadb.primary.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: mariadb
          image: {{ include "mariadb.image" . }}
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy | quote }}
          {{- if .Values.mariadb.primary.containerSecurityContext.enabled }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.mariadb.primary.containerSecurityContext "context" $) | nindent 12 }}
          {{- end }}
          env:
            # Official MariaDB image environment variables
            {{- if .Values.mariadb.auth.rootPassword }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.auth.rootPassword | quote }}
            {{- else }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" . }}
                  key: mariadb-root-password
            {{- end }}
            {{- if not (empty .Values.mariadb.auth.username) }}
            - name: MYSQL_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            {{- if .Values.mariadb.auth.password }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.auth.password | quote }}
            {{- else }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.secretName" . }}
                  key: mariadb-password
            {{- end }}
            {{- end }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.auth.database | quote }}
            {{- if .Values.mariadb.primary.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.mariadb.primary.extraEnvVarsCM .Values.mariadb.primary.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.mariadb.primary.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.mariadb.primary.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.mariadb.primary.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.mariadb.primary.extraEnvVarsSecret }}
            {{- end }}
          {{- end }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mariadb.primary.containerPorts.mysql }}
          {{- if not .Values.mariadb.diagnosticMode.enabled }}
          {{- if .Values.mariadb.primary.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.mariadb.primary.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: {{ .Values.mariadb.primary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mariadb.primary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mariadb.primary.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mariadb.primary.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.mariadb.primary.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.mariadb.primary.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.mariadb.primary.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: {{ .Values.mariadb.primary.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mariadb.primary.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mariadb.primary.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mariadb.primary.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.mariadb.primary.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.mariadb.primary.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.mariadb.primary.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - mariadb-admin ping -uroot -p${MYSQL_ROOT_PASSWORD}
            initialDelaySeconds: {{ .Values.mariadb.primary.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mariadb.primary.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mariadb.primary.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.mariadb.primary.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.mariadb.primary.startupProbe.failureThreshold }}
          {{- end }}
          {{- end }}
          {{- if .Values.mariadb.primary.resources }}
          resources: {{- toYaml .Values.mariadb.primary.resources | nindent 12 }}
          {{- else if ne .Values.mariadb.primary.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.mariadb.primary.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              {{- if .Values.mariadb.primary.persistence.subPath }}
              subPath: {{ .Values.mariadb.primary.persistence.subPath }}
              {{- end }}
            - name: tmp
              mountPath: /tmp
            - name: run-mysqld
              mountPath: /run/mysqld
            {{- if or .Values.mariadb.primary.configuration .Values.mariadb.primary.existingConfigmap }}
            - name: config
              mountPath: /etc/mysql/conf.d
            {{- end }}
            {{- if .Values.mariadb.primary.extraVolumeMounts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.mariadb.primary.sidecars }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: run-mysqld
          emptyDir: {}
        {{- if or .Values.mariadb.primary.configuration .Values.mariadb.primary.existingConfigmap }}
        - name: config
          configMap:
            name: {{ include "mariadb.primary.configmapName" . }}
        {{- end }}
        {{- if .Values.mariadb.primary.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
  {{- if .Values.mariadb.primary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 10 }}
          app.kubernetes.io/component: primary
        {{- if .Values.mariadb.primary.persistence.annotations }}
        annotations: {{- toYaml .Values.mariadb.primary.persistence.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.mariadb.primary.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.mariadb.primary.persistence.size | quote }}
        {{- if .Values.mariadb.primary.persistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.mariadb.primary.persistence.selector "context" $) | nindent 10 }}
        {{- end }}
        {{- include "common.storage.class" (dict "persistence" .Values.mariadb.primary.persistence "global" .Values.global) | nindent 8 }}
  {{- else }}
        - name: data
          emptyDir: {}
  {{- end }}
{{- end }}
